### PR TITLE
Add basic CI with Cirrus

### PR DESCRIPTION
**Pull request by asomers**

### CODE REVIEW

**Comment by asomers** [comment]
Ok, I think the CI setup is working now (but the crate's test don't pass).

**Comment by domodwyer** [comment]
Hmm I wonder if the VMs that run the tests have access to the CPU counters...

I'll take a look this weekend - thanks for everything!

**Comment by domodwyer** [comment]
Ok so I've pretty much confirmed the above suspicion - it seems Cirrus CI uses [Google Cloud](https://cirrus-ci.org/guide/FreeBSD/) to run their VMs. I'm pretty sure GCP doesn't support PMCs in their VMs but found no official statement (there are some examples of [end users](https://stackoverflow.com/questions/40180636/linux-perf-events-profiling-in-google-compute-engine-not-working) not being able to use them in Linux however).

So I figured I'd try using a software counter in CI rather than a hardware counter (though not exactly end-to-end, it would still verify the integration with libpmc) but I can't get any of the [software based events](https://www.freebsd.org/cgi/man.cgi?query=pmc.soft&sektion=3&apropos=0&manpath=FreeBSD+12.2-RELEASE+and+Ports) to work on FreeBSD 12! It may be related to [this bug](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=230984)? Do you have any idea how to pass the software events in 12?

Software events do work on FreeBSD 11 however, so I've enabled CI for 11 only - not a big deal given #7 anyway.

**Comment by domodwyer** [comment]
I've added a commit on top of yours in #12 - I made sure to keep your original commit intact as you did the hard work!

**Comment by asomers** [comment]
I don't think that's correct.  I think performance counters should work in Google Cloud.  You can tell by running `pmccontrol -L` and `pmcstat -p inst_retired.any whoami` in the Cirrus script.  I think it's more likely that the Google Cloud image just doesn't support that one particular counter.  I suspect some of the counters may have been renamed between 11 and 12.  Try `inst_retired.any` instead.

**Comment by domodwyer** [comment]
That's what I was testing with: https://cirrus-ci.com/task/5932156482486272?command=test#L396

`pmccontrol -L` lists plenty of counters, but using them results in:

```
timeout 10 pmcstat -t $$ -p inst_retired.any
pmcstat: ERROR: Cannot allocate process-mode pmc with specification "inst_retired.any": Invalid argument
```

**Comment by asomers** [comment]
Yeah, you're right.  I've been looking into it too, and come to the same conclusion.  Some info on the web suggests that pmc is supposed to work with KVM.  However, it doesn't on my system.

**Pull request closed without merging**
